<?php
	 
 get_header();
  
 ?>
 <section class="full_width page_content <?php if (pmpro_hasMembershipLevel()){ echo member;} ?>">
 	
 	<header class="sub_header full_width">
		<div class="container">
			<h2><?php the_title(); ?></h2>
		</div><!-- .container -->
	 </header>
	 <div class="standard_content">
		 <div class="container">
			 <p>Effective Date: November 1, 2016</p>
			 <p>Last Updated: October 17, 2016</p>
			 <h3>Purpose of Policy</h3>
			 <p>DBBL, LLC (“Company” or “we” or “us”) is committed to respecting the privacy rights of visitors and other users of daricbennett.com (the “Website”). Protecting the privacy and security of consumers’ personal information is very important to us. We created this Privacy Policy (the “Policy”) to give you confidence as you visit and use the Website and to demonstrate our commitment to fair information practices. Therefore, please read this notice carefully to understand what we do with the personal information we collect. This Policy is only applicable to this Website and not to any other website that you may be able to access from the Website, each of which may have data collection and use practices and policies that differ materially from this Policy. By visiting the Website, you consent to the collection and use of your information under the terms of this Policy. </p>
			 <h3>Information We Collect</h3>
			 <p>In operating the Website, we collect personal information from you in several situations. The first is if you sign up or join the email list to receive updates on the newest bass tutorial videos, at which time we collect your e-mail address. Another occurs when you contact us via the “Contact Us” page as you will be asked to provide us with your name and e-mail address. Finally, you may be asked for your name and other information if you leave a comment on a blog or other related forum post. Obviously, you are not required to provide us with information via these methods to browse and enjoy the site.</p>
			 <ul>
				 <li>
				 	<p><span>AUTOMATIC COLLECTION.</span> Our servers automatically recognize visitor’s domain names and IP addresses (the number assigned to computers on the Internet). No personal information about you is revealed in this process. The Website may also gather anonymous “traffic data” that does not personally identify you, but that may be helpful for marketing purposes or for improving the services we offer.</p>
				 </li>
				 <li>
				 	<p><span>COOKIES.</span> From time to time, we may use the standard “cookies” feature of major browser applications. Cookies are small data files that are served by our platform and stored on your device. The Website uses cookies generated by us or third parties for a variety of purposes including to operate and personalize the website. Cookies may also be used to track how you use the site and to target ads to you on other websites. We may use cookies from third party social sites and programs including, but not limited to, Facebook®, Google Plus®, Instagram®, YouTube® and Twitter®. You can choose to disable cookies through your browser or independent programs available online. However, if you choose to disable this function, your experience at our Website may be diminished as some features may not work as they were intended. To opt out of being targeted via these cookies please visit: <a href="www.aboutads.info/choices.">www.aboutads.info/choices.</a></p>
				 </li>
				 <li>
				 	<p><span>SPONSORS AND ADVERTISERS.</span> We may decide to accept sponsorships and advertisements on the Website. Should this occur, you should assume said sponsors and advertisers will be given access to the impressions and click data on their marketing pieces. Your personally identifiable information will not be shared with these sponsors or advertisers. </p>
				 </li>
			 </ul>
			 <h3>Use of Your Information</h3>
			 <p>In operating the Website, we may use your data in the following ways:</p>
			 <ul>
				 <li>
				 	<p><span>PERSONAL INFORMATION.</span> We do not disclose your personally identifiable information to any third parties other than those that we use to facilitate the functioning of the Website, such as a hosting company and e-mail program for mailings. However, we may disclose any information we have for you if required to do so by law or in the good-faith belief that such action is necessary under the following circumstances: (i) to conform to the edicts of the law or comply with legal process served upon us; (ii) to protect and defend our rights, property or the users of the Website; and (iii) to act under exigent circumstances to protect the safety of the public or users of the Website.</p>
				 </li>
				 <li>
				 	<p><span>ANONYMOUS INFORMATION.</span> We use anonymous information to analyze our Website traffic. In addition, we may use anonymous IP addresses to help diagnose problems with our server, to administer our site or to display the content according to your preferences. Traffic and transaction information may also be shared with business partners and advertisers on an aggregated and anonymous basis.</p>
				 </li>
				 <li>
				 	<p><span>USE OF COOKIES.</span> Promotions or advertisements displayed on the Website may contain cookies. We do not have access to or control over information collected by outside advertisers on the Website.</p>
				 </li>
				 <li>
				 	<p><span>SALE OF INFORMATION.</span> In order to accommodate changes in our business, we may sell portions of the Website or our company, including the information collected through this Website. If the Company or substantially all of its assets are acquired by a third party, user information may be one of the assets transferred to the acquirer.</p>
				 </li>
			 </ul>
			 <h3>Security</h3>
			 <p>The Website has security measures in place to prevent the loss, misuse and alteration of the information that we obtain from you, but we make no assurances about our ability to prevent any such loss to you or to any third party arising out of any such loss, misuse or alteration. While we strive to protect your personal data, we simply cannot guarantee the security of any information you provide us, and you do so at your own risk. </p>
			 <h3>Third Party Websites</h3>
			 <p>From time to time, the Website may contain links to other websites. If you choose to visit those websites, it is important to understand our Privacy Policy and Terms of Use do not extend to those sites. In fact, these third party websites may independently solicit and collection information from you. As such, it is your responsibility to review the privacy policies and terms of use of those websites to confirm that you understand and agree with the terms.</p>
			 <h3>Contacting Us</h3>
			 <p>If you have any questions about this Policy or our practices related to the Website, please feel free to contact us using the “Contact” link on the menu located at the top of the Website.</p>
			 <h3>Updates & Changes</h3>
			 <p>We reserve the right, at any time, to add to, change, update and modify this Policy to reflect changes in our practices. Any changes to this Policy in the future will be posted to the Website. It is your responsibility to review this Policy from time to time to ensure that you accept all of its terms. If you have signed up for e-mail communications from us, we will notify you of changes to the Policy by e-mail as well. Your continued use of the Website will indicate your agreement to such changes.</p>
		 </div>
	 </div>
 </section>