<?php
	 
 get_header();
  
 ?>
 <section class="full_width page_content <?php if (pmpro_hasMembershipLevel()){ echo member;} ?>">
 	
 	<header class="sub_header full_width">
		<div class="container">
			<h3><?php the_title(); ?></h3>
		</div><!-- .container -->
	 </header>
	 <div class="standard_content">
		 <div class="container">
			 <p>Effective Date: November 1, 2016</p>
			 <p>Last Updated: October 17, 2016</p>
			 <h3>Acceptance of Terms</h3>
			 <p>Welcome to daricbennett.com (“Website”), the website of DBBL, LLC, a Missouri limited liability company (“Company”, “we” or “us”). These Terms of Use (“Terms”) and the related Privacy Policy (“Policy”) incorporated herein by reference, see http://daricbennett.com/privacy, govern your access to and use of the Website and how we use your information, whether as a visitor or a registered member. Therefore, we recommend you (“you”, “your” or “User”) thoroughly read these Terms before using the Website and/or making any purchases from us. If you do not agree to the Terms and/or Policy, please do not use the Website.</p>
			 <p>Your use of the Website is only on the condition that you agree to abide by the following terms:</p>
			 <p>The Company reserves the right to update these Terms at any time without notice to User. The most current version of the Terms can be reviewed by clicking on the “Terms of Use” link located at the bottom of our Website.</p>
			 <h3>Updates & Changes</h3>
			 <p>We reserve the right, at any time and in our sole discretion, to add to, change, update and modify these Terms. All changes are effective immediately when we post them, and apply to any and all access and use of the Website thereafter. It is your responsibility to review the Terms from time to time to ensure that you accept all of its terms. If you have signed up for e-mail communications from us, we will notify you of changes to the Terms by e-mail as well. Your continued use of the Website will indicate your agreement to such changes.</p>	
			 <h3>Personal Use Only</h3>
			 <p>All content that you will receive or to which you will have access during your subscription is for your personal use only and may not be shared, resold, auctioned or transferred to another person or entity in any manner. As a condition of accessing the Website, you agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Website. The Company will enforce its rights and initiate appropriate legal action against Users who violate these Terms. </p>
			<h3>Account, Password and Security</h3>
			<p>The Services may require you to open an account (hereinafter “User Account”), in which case User must complete the registration process by providing us with current, complete and accurate information as prompted by the applicable registration form. User also will choose a password and a user name. User is entirely responsible for maintaining the confidentiality of User’s password and account. Furthermore, User is entirely responsible for any and all activities that occur under User’s account. User agrees to notify us immediately of any unauthorized use of User’s account or any other breach of security. We are not liable for any loss that User may incur as a result of someone else using User’s password or account, either with or without User’s knowledge. However, User will be held liable for losses incurred by us or another party due to someone else using User’s account or password. User may not use anyone else’s account at any time.</p>
			 <h3>Age Requirement</h3>
			 <p>The Services are available to individuals age 13 and over. If you are between the ages of 13 and the age of majority where you live, you must review these Terms with your parent or guardian to confirm that you and your parent or guardian understand and agree to it. By using the Website, you agree to provide us with accurate information concerning your age and identity if we request it. You also agree not to assist children under the age of 13 in accessing the Website or to attempt to contact children under 13 through the Website.</p>
			 <h3>Modifications to the Site</h3>
			 <p>The Company shall have the right at any time to modify, suspend or discontinue, temporarily or permanently, the Website, or any part thereof, from time to time, for any reason and without notice. We endeavor to keep the information and materials contained on the Website current, however, such information and materials are subject to change at any time without notice to you and the featured information on the Website may not immediately reflect such changes.</p>
			 <h3>Links to Other Third Party Websites</h3>
			 <p>The Services may contain links to third party websites that are not owned or controlled by us. Therefore, we have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third party websites. In addition, the Company will not and cannot censor or edit the content of any third-party site. By using the Services, you expressly relieve us from any and all liability arising from your use of any third-party website. Accordingly, we encourage you to be aware when you leave the Services and/or Website and to read the terms and conditions and privacy policy of each other website that you visit.</p>
			 <h3>Subscription and Payment</h3>
			 <p>After browsing our Website, we hope that you will be interested in subscribing to our Services. Users may access the Website and/or Services as a “Full Member,” “Free Member” or a “Visitor.” “Members” may include a variety of designated levels of members who may be charged for services according to the terms of the particular offer, or registered free trial members (“Free Member”), or other membership levels. “Visitors” are users that have not registered for an account with access to and use of certain aspects of the Services offered on the Website, which may be restricted and only available to certain Members. 
			 </p>
			 <p>In order to have full access to any and all content found on the Website, the Company offers users the ability to become a “Full Member” by paying a monthly subscription fee of $9.99 (“Subscription Fee”). As a Full Member, you will enjoy advanced bass lessons, a community and forum for users to ask questions and discuss relevant subject matter. The Subscription Fee is reoccurring on a monthly basis. On the other hand, for those of you who would like to explore our Services before purchasing, we offer a free 3-day trial. Put simply, as a Free Member with a free 3-day trial, you have access to the same Services that a Full Member has for a limited 3-day period. Such trials may require you to register with a valid credit card to commence. Users that sign up for a free trial membership will be automatically renewed at $9.99 at the end of the trial period unless the user cancels the membership at least before the end of the trial. You can cancel a free trial online or by contacting the Company’s customer support. After cancellation of a free trial, you can continue as a Visitor with reduced benefits or access. </p>
			 <p>In order to use the Services as a Full Member or Free Member, you must provide account information for at least one valid payment method. We make the following methods of payment available: Credit Card and PayPal (each a “Payment Method”). You hereby authorize us to run credit card authorizations on all credit cards provided by you, to store credit card and banking or other financial details as your method of payment for the Services, and to charge your credit card or any other Payment Method. You agree to pay all applicable fees for your memberships and use of our paid Services, plus any applicable taxes or other charges as may be required, when due and payable. All fees and charges are payable in advance and non-refundable, including after cancellation. <span>MEMBERSHIPS WILL AUTOMATICALLY RENEW AND YOUR CREDIT CARD OR OTHER PAYMENT METHOD PROVIDED WILL BE CHARGED ON THE FIRST DAY OF EACH RENEWAL PERIOD UNTIL YOUR MEMBERSHIP IS TERMINATED BY US OR CANCELLED BY YOU.</span> If you wish to cancel your membership, please contact us at admin@daricbennett.com.</p>
			 <p>By providing Payment Method information through the Website, you represent, warrant, and covenant that: you are legally authorized to provide such information to us; you are legally authorized to perform payments using the Payment Method; and such action does not violate the terms and conditions applicable to your use of such Payment Method or applicable law. When you authorize a payment using a Payment Method via the Website, you represent, warrant, and covenant that there are sufficient funds or credit available to complete the payment using the designated Payment Method. To the extent that any amounts owed under this Agreement cannot be collected from your Payment Method, you will be and are solely responsible for paying such amounts by other means.</p>
			 <h3>Account Cancellation</h3>
			 <p>You may cancel your account at any time throughout our Services. Additionally, we may cancel your account in our sole discretion for any reason including but not limited to inactivity or misuse. Even if your account is cancelled, your comments and other data you have shared via the Services may persist within the Service after cancellation of your account.</p>
			 <h3>Intellectual Property</h3>
			 <p>All content or other materials available on the Site, including but not limited to code, images, text, layouts, arrangements, displays, illustrations, audio and video clips, HTML files, and all other content, are the property of the Company and/or its affiliates or licensors, and are protected by copyright, patent, and/or other proprietary intellectual property rights under the United States or foreign laws. User may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. Except as otherwise expressly permitted under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material will be permitted without our express permission and the copyright owner. In the event of any permitted copying, redistribution or publication of copyrighted material, no changes or deletion of author attribution, trademark legend or copyright notice shall be made. User acknowledges that it does not acquire any ownership rights by downloading copyrighted material. The burden of determining that your use of any information, software, or any other content on the Website is permissible rests with you.</p>
			 <h3>Our Responsibility for Material Uploaded or Submitted to Website by User(s)</h3>
			 <p>We do not screen, edit or review material submitted by users and therefore we cannot accept any responsibility or responsibility for any material found on the Website. Any and all content uploaded or submitted to the Website by Users no way reflect the views or ideals of the Company. The Company has the right, but not the obligation, to monitor any and all information transmitted or received through the Website. The Company, in its sole discretion and without further notice to you, shall have the right to edit, censor, prohibit the transmission and/or receipt, or remove any material that it finds to be inappropriate, in violation of the provisions hereof or otherwise objectionable. </p>
			 <h3>User Conduct and Posting</h3>
			 <p>User shall use the Website in accordance with all applicable laws. User agrees not to post or transmit any information through our Website which: (a) infringes the rights of others or violates their privacy or publicity rights; (b) is unlawful, threatening, abusive, defamatory, libelous, vulgar, obscene, profane, indecent or otherwise objectionable; (c) is protected by copyright, trademark or other proprietary right without the express written permission of the owner of such right; or (e) contains unauthorized or malicious software such as viruses. YOU AGREE TO INDEMNIFY AND HOLD THE COMPANY AND ANY OF ITS RELATED ENTITIES, BOARD MEMBERS, EMPLOYEES, AGENTS AND REPRESENTATIVES HARMLESS FROM AND AGAINST, AND SHALL REIMBURSE THE COMPANY FOR ANY LIABILITY, DAMAGE, CLAIM, LOSS, COST OR EXPENSE, INCLUDING, WITHOUT LIMITATION, COURT COSTS AND REASONABLE ATTORNEYS’ FEES, WHICH MAY BE INCURRED BY THE COMPANY AS A RESULT OF THE MATERIAL YOU UPLOAD, POST, OR TRANSMIT TO THE WEBSITE. We have the right, but not the obligation, to remove content for any reason. </p>
			 <p>You are responsible for any content you post to the Website and the consequences of sharing or publishing such content with others or the general public. Any conduct by a User that, as determined in our sole discretion, restricts or inhibits any other User from using or enjoying the Website will not be permitted. Always use caution when posting any personally identifiable information on the Website. WE ARE NOT RESPONSIBLE FOR THE CONSEQUENCES OF SHARING OR POSTING ANY PERSONAL OR OTHER INFORMATION ON THE Website.
			 </p>
			 <p>By submitting and/or posting material to the Website, you grant us and our assigns, agents, and licensees the irrevocable, royalty free, perpetual, worldwide right and license to use, reproduce, modify, display, perform, distribute, adapt, create derivative works, and syndicate the uploaded content in any medium now know or hereafter discovered. Additionally, we own all rights, title, and interests in any compilation, collective work or other derivative work created by us using or incorporating your content, though excluding your original content. </p>
			 <h3>Technical Requirements</h3>
			 <p>You shall be responsible for meeting and maintaining the minimum technical requirements for your selected purchase in order to access certain features of the Website and corresponding Services. Please contact us to understand specific requirements.</p>
			 <h3>Digital Signature</h3>
			 <p>By registering for a User Account, or by clicking to accept the Terms when prompted on the Website, you are deemed to have executed this Agreement electronically, effective on the date you register your User Account, pursuant to the U.S. Electronic Signatures in Global and National Commerce Act (the E-Sign Act) (15 U.S.C. § 7001, et seq.). Your User Account registration constitutes an acknowledgment that you are able to electronically receive, download, and print these Terms, and any amendments.</p>
			 <h3>Limitation of Claims</h3>
			 <p>Any action or claim against the Company must be brought by the User within one (1) year following the date the claim first accrued, or shall be deemed waived.</p>
			 <h3>Disclaimer of Warranty and Limitation of Liability</h3>
			 <p>You acknowledge and agree that no warranties of any kind are made with respect to the Website. Moreover, you acknowledge that the material and links provided through the Website are compiled from sources that are beyond the control of the Company. As such, except as expressly provided otherwise, the Company disclaims any and all responsibility and liability for the timeliness, sequence, quality, accuracy, content, completeness, legality, reliability, operability and availability of information or material contained on the website. The website may contain inaccuracies or typographical errors. We disclaim any responsibility for the deletion, failure to store, misdelivery or untimely delivery of any information or material in respect to the website or the use thereof.</p>
			 <p>Any communications sent to you via the Website or otherwise from the Company (including, without limitation, in the form of newsletters, electronic mail or via telephone), and the contents of the Website (including, without limitation, any technology, financial, investment, corporate or tax information) are provided for informational and educational purposes only and are not intended to provide legal, investment, financial or tax advice and should not be relied upon in that regard. Therefore, you should independently consult a lawyer or tax advisor.</p>
			 <p>THE INFORMATION AND MATERIAL FROM OR THROUGH THE WEBSITE IS PROVIDED “AS IS, WITH ALL FAULTS”. THE COMPANY EXPRESSLY EXCLUDES AND DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE DISCLAIMER OF ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE INFORMATION AND SERVICES MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS. WE AND OUR AFFILIATED PARTIES HAVE NO LIABILITY WHATSOEVER FOR YOUR USE OF ANY INFORMATION OR SERVICE. IN PARTICULAR, BUT NOT AS A LIMITATION THEREOF, WE AND OUR EMPLOYEES. AGENTS, LICENSORS, CONTRACTORS AND AFFILIATED PARTIES ARE NOT LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES (INCLUDING DAMAGES FOR LOSS OF BUSINESS, LOSS OF PROFITS, LITIGATION, OR THE LIKE), WHETHER BASED ON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. WE DO NOT WARRANT THAT THE WEBSITE WILL MEET YOUR REQUIREMENTS OR THAT THE OPERATION OF THE WEBSITE WILL BE UNINTERRUPTED OR ERROR-FREE. THE NEGATION OF DAMAGES SET FORTH ABOVE IS A FUNDAMENTAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN US AND YOU. THIS WEBSITE AND THE INFORMATION WOULD NOT BE PROVIDED WITHOUT SUCH LIMITATIONS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US THROUGH THE WEBSITE SHALL CREATE ANY WARRANTY, REPRESENTATION OR GUARANTEE NOT EXPRESSLY STATED IN THIS AGREEMENT. ALL RESPONSIBILITY AND LIABILITY FOR ANY DAMAGES CAUSED BY VIRUSES CONTAINED WITHIN OR TRANSMITTED THROUGH THE WEBSITE IS DISCLAIMED. WE WILL NOT BE LIABLE TO YOU FOR ANY INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES OF ANY KIND THAT MAY RESULT FROM USE OF OR INABILITY TO USE OUR WEBSITE. WE MAKE NO REPRESENTATIONS, WARRANTIES OR ASSURANCES AS TO THE AVAILABILITY OF THE WEBSITE. OUR MAXIMUM LIABILITY TO YOU UNDER ALL CIRCUMSTANCES WILL BE EQUAL TO THE PURCHASE PRICE YOU PAY FOR ANY GOODS, SERVICES, OR INFORMATION HEREIN.</p>
			 <h3>Indemnification</h3>
			 <p>You agree to indemnify, defend and hold us and our partners, attorneys, staff and affiliates harmless from any liability, loss, claim and expense, including reasonable attorneys’ fees, related to your violation of these Terms or use of the Website.</p>
			 <h3>Class Action/Jury Trial Waiver</h3>
			 <p>WITH RESPECT TO ALL PERSONS AND ENTITIES, REGARDLESS OF WHETHER THEY HAVE OBTAINED OR USED THE SERVICE FOR PERSONAL, COMMERCIAL OR OTHER PURPOSES, ALL CLAIMS MUST BE BROUGHT IN THE PARTIES’ INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION OR OTHER REPRESENTATIVE PROCEEDING. THIS WAIVER APPLIES TO CLASS ARBITRATION, AND, UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS. YOU AGREE THAT, BY ENTERING INTO THIS AGREEMENT, YOU AND WE ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING OF ANY KIND.</p>
			 <h3>Termination</h3>
			 <p>You agree that the Company, in its sole discretion, may terminate your use of the Website or your participation in it thereof, for any reason or no reason at all, and that the Company shall not have any liability to you for any such action. We reserve the right to access your account and records on a case-by-case basis to investigate complaints or allegations of abuse, infringement or other unauthorized uses of the Website or the Service. Additionally, the Company may at any time, without prior notice and in its sole discretion, remove any User content and/or terminate a User Account for submitting material that violates the Terms. </p>
			 <h3>Procedure of Reporting Copyright Infringement (DMCA Policy)</h3>
			 <p>We respect the rights of all copyright holders and therefore have adopted a policy that provides for the termination in appropriate circumstances of users who infringe the rights of copyright holders. If you are a copyright owner or agent and believe that any of the content on the Website infringes upon your copyright, please submit notice, pursuant to the Digital Millennium Copyright Act (17 U.S.C. § 512) to our Copyright Agent with the following information: (i) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright; (ii) a description of the copyrighted work that you claim has been infringed; (iii) the URL of the location containing the material that you claim is infringing; (iv) your address, telephone number, and e-mail address; (v) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and (vi) a statement by you made under penalty of perjury that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf. You acknowledge that if you fail to comply with all of the requirements of this Section, your DMCA notice may not be valid.</p>
			 <p>Our Copyright Agent can be reached as follows:</p>
			 
			 <div class="address">
				 <h4><span>By E-Mail:</span> admin@daricbennett.com</h4>
				 <h4><span>By Mail:</span> ATTN: Copyright Agent</h4>
				 <h4><span>Address:</span> PO Box 240213</h4>
				 <h4>Ballwin, MO 63024</h4>
			 </div>
			 <p><span class="underline">Counter-Notice.</span> If you believe your content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner’s agent, or pursuant to the law, to post and use the material in your content, you must submit a counter-notice containing the following information to the Copyright Agent listed above: (i) your physical or electronic signature; (ii) your name, address and phone number; (iii) identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled; (iv) a statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; (v) your consent to the jurisdiction of a federal court in the district where you live (if you are in the U.S.) or your consent to the jurisdiction of a federal court in the district where your service provider is located (if you are not in the U.S.); and (vi) your consent to accept service of process from the person who provided the notification under 17 U.S.C. § 512(c)(1)(C) or an agent of such person.</p>
			 <p>If a counter-notice is received by the Copyright Agent, the Company may send a copy of the counter- notice to the original complaining party informing that person that it may replace the removed content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, in the Company’s sole discretion.</p>
			 <p>Please note that you may be liable for any damages (including costs and attorneys’ fees) if you materially misrepresent that your content and or activity is not infringing the copyrights of others. If you are not sure if your content or activity infringes on the copyrights of others, we advise you to consult with an attorney. </p>
			 <h3>Choice of Law and Jurisdiction</h3>
			 <p>These Terms shall be construed in accordance with the laws of the State of Missouri without reference to any conflict of law principles. Further, any such claim or cause of action shall be brought exclusively in the state or federal courts located in St. Louis, St. Louis County, Missouri, and you agree to submit to the exclusive personal jurisdiction of such courts and hereby appoint the Secretary of State of Missouri as your agent for service of process. </p>
			 <h3>Severability</h3>
			 <p>If a court of law finds that any provision of these Terms is invalid or unenforceable, the remaining provisions will continue to be valid and enforceable. Any unenforceable provision will be replaced by a mutually acceptable provision which comes closest to the intention of the parties at the time the original provision was agreed upon.</p>
			 <p>To the extent that anything in or associated with the Website is in conflict or inconsistent with these Terms, these Terms shall take precedence. Our failure to enforce a provision of these Terms shall not be deemed a waiver of such provision nor of the right to enforce such provision.</p>
			 <h3>Miscellaneous</h3>
			 <p>These Terms and any operating rules for the Website established by the Company constitute the entire agreement of the parties with respect to the subject matter hereof, and supersede all previous written or oral agreements between the parties with respect to such subject matter. </p>
			 <p>We may assign this contract at any time without notice, however you may not assign this contract to anyone else.</p>
			 <p>This is the entire agreement between the parties and may not be modified except in writing signed by both parties.</p>
			 <p>The section headings used herein are for convenience only and shall not be given any legal import.</p>
			 <h3>Your Comments and Concerns</h3>
			 <p>All other feedback, comments, requests for technical support and other communications relating to the Website should be directed to: admin@daricbennett.com.</p>
			 <p>Thank you for visiting the Website.</p>
		 </div>
	 </div>
 </section>